config/routes.rb
Rails.application.routes.draw do

  #for scheduling
	require 'sidekiq/web'
	mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcomes#index"
  resources :posts  do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	#associations
	belongs_to :user
	belongs_to :post

	#validation
	validates_presence_of :comment

	# callback to send mail
	after_create :send_email_for_post_notify

	private 

	def send_email_for_post_notify
		PostNotifyWorker.perform_async(self.id)
	end
end

app/models/post.rb
class Post < ApplicationRecord
	#associations
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_one_attached :avatar
	#validation
	validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #associations
  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
  expose :comment, id: ->{ params[:comment_id] || params[:id] }
 
 # POST  /posts/:post_id/comments
	def create
		post = Post.find_by(params[:post_id])
		@comment = post.comments.build(comment_params)
		@comment.user = current_user
    if @comment.save
      flash[:success] = "comments created successfully."
      redirect_to request.referer
    else
    	flash[:error] = @comment.errors.full_messages
    	redirect_to posts_path
    end
	end

  #GET /posts/:post_id/comments/:id/edit
  def edit
    @comment = comment
  end

  #PATCH  /posts/:post_id/comments/:id
  def update
    comment.update(comment_params)
    redirect_to posts_path
  end

	private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  expose :post, id: ->{ params[:id] }

  # GET /posts/
  def index
  	public_posts = Post.where(is_public: true)
    user_post = current_user.posts
    @posts =  public_posts + user_post
  end

  # GET /posts/new/
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created successfully."
      redirect_to posts_path
    else
    	flash[:error] = @post.errors.full_messages
    	render 'new'
    end   
  end

  # GET /posts/:id
  def show
  end

  # DELETE /posts/:id
  def destroy
  	post.destroy
  	redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :is_public, :avatar)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/comments/_form.html.erb
<%= form_for post.comments.new,  url: post_comments_path(post.id) do |f| %>
	<div class="field">
	  <%= f.label :comment %><br />
	  <%= f.text_field :comment, autofocus: true %>
	</div>

	<div class="actions">
	  <%= f.submit "Submit" %>
	</div>
<% end %>
 

app/views/comments/edit.html.erb
<%= form_for @comment,  url: post_comment_path(comment.id), method: :patch do |f| %>
	<div class="field">
	  <%= f.label :comment %><br />
	  <%= f.text_field :comment, autofocus: true %>
	</div>

	<div class="actions">
	  <%= f.submit "Submit" %>
	</div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Demo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
      </li>
      <li class="nav-item nav-link">
        <% if user_signed_in? %>
	       <%= link_to "Sign Out ", destroy_user_session_path, method: :delete  %>
        <% end %>	
      </li>
      <% unless user_signed_in? %>
        <li class="nav-item nav-link">
	       <%= link_to "Sign in ", new_user_session_path  %>
        </li>
        <li class="nav-item nav-link">
	        <%= link_to "Sign up ", new_user_registration_path  %>
        </li>
      <% end %>	
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>


<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
    $('.alert').fadeOut();
    }, 2000);
  })
</script>

app/views/posts/_form.html.erb
<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title, autofocus: true %>
</div>

<div class="field">
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</div>

<div class="field">
  <%= f.check_box :is_public %>
  <%= f.label :is_public %>
</div>

<div class="field">
	 <%= f.label :Image %><br/>
	<%= f.file_field :avatar %>
</div><br/>

<div class="actions">
  <%= f.submit "Submit" %>
</div>

app/views/posts/index.html.erb
<% @posts.uniq.each do |post| %>
	<%= post.title %>
	<%= post.description %>
	<%= link_to "Show", post_path(post) %>
	<%= link_to "Destroy", post_path(post), data: {:confirm => 'Are you sure?'}, :method => :delete if current_user.id == post.user_id %>
	</br>
<% end %>

app/views/posts/new.html.erb
<div>
  <%= form_for @post do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Title</h1><%= post.title %>
<h1>Description</h1><%= post.description %>
<h1>Image</h1><%= image_tag post.avatar if post.avatar.attached? %>

<%= render 'comments/form' %>

<h1>Comment</h1>

<% post.comments.each do |comment| %>
	<%= comment.comment %>
		<%= link_to "Edit", edit_post_comment_path(post, comment.id) if comment.id.present? %>
	</br>
<% end %> 

app/views/welcomes/index.html.erb
<%= link_to "Create Post", new_post_path %></br>
<%= link_to "All Post", posts_path %>